### ISSUE TITLE
Natural fauna keeps making the game crash

### ISSUE THREAD

**Issue by DAMENCARMEN** [0SoggyMustache0/ZAWA#120]
every time i try to play my mod pack it says this

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from NaturalFauna (faunanatural)

this is the crash report

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 6/27/20 1:39 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from NaturalFauna (faunanatural)
Caused by: java.lang.NoClassDefFoundError: com/ikerleon/naturalfaunamod/entity/EntityCamel
	at com.ikerleon.naturalfaunamod.init.EntityInit.registerEntity(EntityInit.java:30)
	at com.ikerleon.naturalfaunamod.init.EntityInit.register(EntityInit.java:23)
	at com.ikerleon.naturalfaunamod.proxies.CommonProxy.preInit(CommonProxy.java:27)
	at com.ikerleon.naturalfaunamod.NaturalFaunaMain.preInit(NaturalFaunaMain.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.ikerleon.naturalfaunamod.entity.EntityCamel
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 44 more
Caused by: java.lang.NoClassDefFoundError: org/zawamod/entity/base/ZAWABaseLand
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 46 more
Caused by: java.lang.ClassNotFoundException: org.zawamod.entity.base.ZAWABaseLand
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 50 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 557772416 bytes (531 MB) / 1319632896 bytes (1258 MB) up to 3008888832 bytes (2869 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3228m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 19 mods loaded, 19 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                | Version           | Source                                        | Signature                                |
	|:----- |:----------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft         | 1.12.2            | minecraft.jar                                 | None                                     |
	| LCH   | mcp               | 9.42              | minecraft.jar                                 | None                                     |
	| LCH   | FML               | 8.0.99.99         | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge             | 14.23.5.2854      | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | biomesoplenty     | 7.0.1.2441        | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar | None                                     |
	| LCH   | bookworm          | 1.12.2-2.5.2.1    | bookworm-1.12.2-2.5.2.1.jar                   | None                                     |
	| LCH   | ctm               | MC1.12.2-1.0.2.31 | CTM-MC1.12.2-1.0.2.31.jar                     | None                                     |
	| LCH   | chisel            | MC1.12.2-1.0.2.45 | Chisel-MC1.12.2-1.0.2.45.jar                  | None                                     |
	| LCH   | customspawner     | 3.11.4            | CustomMobSpawner-3.11.5.jar                   | None                                     |
	| LCH   | mocreatures       | 12.0.5            | DrZharks MoCreatures Mod-12.0.5.jar           | None                                     |
	| LCH   | dynamictrees      | 1.12.2-0.9.8      | DynamicTrees-1.12.2-0.9.8.jar                 | None                                     |
	| LCH   | dynamictreesbop   | 1.12.2-1.4.1e     | DynamicTreesBOP-1.12.2-1.4.1e.jar             | None                                     |
	| LCH   | exoticbirds       | 1.0               | Exotic Birds 1.12.2-3.2.0.jar                 | None                                     |
	| LCH   | zawa              | 1.12.2-2.1.0      | zawa-1.12.2-2.1.0.jar                         | 3ee471ded1bba54aa82f4f5ca5ca82dd67b8ef42 |
	| LCH   | lilcritters       | 1.12.2-1.1.0.0    | lilcritters-1.12.2-1.1.0.0.jar                | None                                     |
	| LCE   | faunanatural      | 1.12.2-1.5.1      | NaturalFauna Mod-1.12.2-1.5.1.jar             | None                                     |
	| LC    | tropicraft        | 7.1.9.115         | tropicraft-MC1.12.2-7.1.9.115.jar             | None                                     |
	| LC    | worldedit         | 6.1.10            | worldedit-forge-mc1.12.2-6.1.10-dist.jar      | None                                     |
	| LC    | betteranimalsplus | 9.0.1             | betteranimalsplus-1.12.2-9.0.1.jar            | None                                     |

	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 442.05' Renderer: 'GeForce GTX 1660 SUPER/PCIe/SSE2'

reminder that all of the addons are updated and every time i play without natural fauna it works fine please fix this

**Comment by 0SoggyMustache0** [comment]
Natural fauna is no longer recieving updates.
