### ISSUE TITLE
[Bug] A thing does some other thing when a thing is doing something.

### ISSUE THREAD

**Issue by andrewminer** [0SoggyMustache0/ZAWA#97]
**Describe the bug**

Polar bears cause a crash, seemingly when eating another creature.

**To Reproduce**

1. Spawn some polar bears.
2. Spawn some creatures whom the bears would like to eat.
3. Wait for the bears to attack the other creatures.  The server crashes.

**Expected behavior**

Feast.

**Crash Report or Game Log**

[crash-report.txt](https://github.com/0SoggyMustache0/ZAWA/files/4768725/crash-report.txt)

**Please complete the following information):**
 - Mod Version Number : 2.0.2
 - Bookworm Version Number : 2.5.1
 - Forge Version Number : 14.23.5.2847
 - Are other mods installed? : See: https://github.com/andrewminer/ad-astra/
 - Is OptiFine installed? : No.
 - Is this bug present in single player or on a server or both? : Only seen on server.

**Comment by 0SoggyMustache0** [comment]
Youre on an old version of zawa, you have core mods, and you didn't remove all mods besides zawa and bookworm before leaving this report. Follow the template properly.

**Comment by andrewminer** [comment]
It's obviously your call to ignore this issue, and I won't fight you about it.  It's no fun to try to track down crazy incompatibilities with other mods or try to diagnose some random stranger's set up.   On the other hand, I did take the trouble to grab the crash data for your benefit instead of simply ignoring it, and the stack trace seems reasonably clear in this case:
```
java.lang.NoSuchMethodError: org.zawamod.entity.land.EntityPolarBear.playEatEffect()V
	at org.zawamod.entity.land.EntityPolarBear.func_70636_d(EntityPolarBear.java:205)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at org.zawamod.entity.base.ZAWABaseLand.func_70071_h_(ZAWABaseLand.java:585)
	at org.zawamod.entity.land.EntityPolarBear.func_70071_h_(EntityPolarBear.java:225)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by 0SoggyMustache0** [comment]
I appreciate that you took the time to upload a crash report and I will look and see if it is an issue because it does point to a zawa method. However, it would be nice if you were at least running the latest version of my mod. If it is an issue with the mod then it will be fixed in the next update.

**Comment by andrewminer** [comment]
I'll make sure to pull down the latest ZAWA version when I next update the server, and I'll let you know if this continues to be an issue.  I've got a number of players on the server, so I try batch up changes (~ 1x per week) so they don't get too annoyed with me.  ;-)
